### ISSUE TITLE
tests/test_run.py  missing data file:  data/test_data/simu_bball_4.txt

### ISSUE THREAD

**Issue by camlspotter** [camlspotter/learnHA#2]
How to reproduce:

```
$ pipenv run python3 -m unittest tests.test_run.TestLearnHA.test_runLearnHA_bball_withAnnotate
Running test runLearnHA module with Bouncing Ball model with type annotation
E
======================================================================
ERROR: test_runLearnHA_bball_withAnnotate (tests.test_run.TestLearnHA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jun/hal/learnHA/tests/test_run.py", line 171, in test_runLearnHA_bball_withAnnotate
    list_of_trajectories, stepsize, system_dimension = parse_trajectories(input_filename)
  File "/home/jun/hal/learnHA/utils/parse_parameters.py", line 230, in parse_trajectories
    with open(input_filename, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/test_data/simu_bball_4.txt'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

**Comment by camlspotter** [comment]
`run_results_main_learn_models.sh` of HybridLearner with changing some parameters from 64 to 4 creates files required:

```
commit d6e2fb21b159480c62f47677646dd7d4b2b9c9c8
Author: Jun Furuse <jun.furuse@dailambda.jp>
Date:   Wed Jul 24 17:43:07 2024 +0900

    Adds missing test data files
```
