### ISSUE TITLE
libsvm carries binaries

### ISSUE THREAD

**Issue by camlspotter** [camlspotter/learnHA#3]
This is unsettling to me:

```
$ find infer_ha/libsvm/ | grep 'exe\|so'
infer_ha/libsvm/windows/svm-scale.exe
infer_ha/libsvm/windows/svm-train.exe
infer_ha/libsvm/windows/svm-predict.exe
infer_ha/libsvm/windows/svm-toy.exe
infer_ha/libsvm/lib/libsvm.so.2
```

**Comment by camlspotter** [comment]
It looks like  a copy https://pypi.org/project/libsvm/ .  Why this is required?
Cannot we install the official libsvm instead?

**Comment by camlspotter** [comment]
infer_ha.test_svm of `run_tests` fails out of the box:

```
======================================================================
ERROR: infer_ha.test_svm (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: infer_ha.test_svm
Traceback (most recent call last):
  File "/home/jun/.pyenv/versions/3.8.19/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/jun/.pyenv/versions/3.8.19/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/jun/hal/learnHA/infer_ha/test_svm.py", line 4, in <module>
    from libsvm.svmutil import svm_train, svm_predict, svm_problem, svm_parameter
ModuleNotFoundError: No module named 'libsvm'
```

`infer_ha/` has a copy of `libsvm` but not properly loaded at tests.  Weird...

**Comment by camlspotter** [comment]
I concluded that tests use different versions of libsvm!

- infer_ha.test_svm fails if libsvm is not installed.
- tests.test_run fails if the copy of libsvm is removed.
